common: &common
  adapter: postgresql
  username: postgres
  password: 180lbs

development:
  <<: *common
  database: daycare_decisions_development

test:
  <<: *common
  database: daycare_decisions_test

production:
  <<: *common
  database: daycare_decisions_production
